name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: DTransfer Folder to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/YourCabs || git@github.com:NaveenShetter1/YourCabs.git
          cd /home/ubuntu/YourCabs
          git pull origin main
          EOF

      - name: Verify Folder on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/YourCabs
          #YourCabs  # Replace with your actual ML script
          EOF
