name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Triggers on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            if [ ! -d "/home/ubuntu/YourCabs/.git" ]; then
              cd /home/ubuntu
              git clone https://github.com/NaveenShetter1/YourCabs.git
            else
              cd /home/ubuntu/YourCabs
              git pull origin main
            fi
          EOF

      - name: Verify on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ubuntu/YourCabs
            ls -l
          EOF
